//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunchClock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feuille
    {
        public string numero_employe { get; set; }
        public string annee { get; set; }
        public string numero_semaine { get; set; }
        public string jour1 { get; set; }
        public string jour2 { get; set; }
        public string jour3 { get; set; }
        public string jour4 { get; set; }
        public string jour5 { get; set; }
        public string weekend1 { get; set; }
        public string weekend2 { get; set; }
        public string nume_annee_numms { get; set; }
    }
}
